language: node_js

node_js:
  - "6"
  - "7"

sudo: false

before_script:
  - npm install -g eslint-config-standard eslint-plugin-standard eslint-plugin-promise ava

cache:
  directories:
    - node_modules
