language: node_js

node_js:
  - "6"
  - "7"

sudo: false

before_script:
  - npm install -g eslint
  - npm install -g eslint-config-standard
  - npm install -g ava

cache:
  directories:
    - node_modules
